os: linux
dist: xenial
services:
  - docker
before_install:
  - sudo apt update
  - docker-compose --version
  # Docker compose commands can be used here.
before_script:
  - sudo chmod +x $TRAVIS_BUILD_DIR/php-app/run.sh
script:
  - docker run -v $TRAVIS_BUILD_DIR/php-app:/app gilbitron/php5.6-mysql
